### ISSUE TITLE
Relative paths in hsi_core

### ISSUE THREAD

**Issue by mzarowka** [mzarowka/HSItools#36]
The path stored in .rds is an absolute path, leading to reprocessing issues when the directory structure is changed.

**Comment by DaveEdge1** [comment]
added a helper function for this: change_output_dir()

**Comment by mzarowka** [comment]
@DaveEdge1 Can't be sure if something broke with updates, or I'm not doing it right, but change_output_dir() throws an error now.

```
Error in `if (basename(run_core_output$directory) != basename(newDir)) ...`:
! missing value where TRUE/FALSE needed
Hide Traceback
    ▆
 1. └─HSItools::change_output_dir(test)
```

**Comment by mzarowka** [comment]
@DaveEdge1 once the HSItools.rds is read back into the environment, the $directory is missing entirely.

**Comment by mzarowka** [comment]
Fixed missing $directory. Closing, for now.
